Feature/get artist
lordmkichavi-andes/MISW4203-202415-Grupo008 pull request #59
Opened 2024-11-09 15:38 UTC by lordmkichavi-andes

2024-11-09 18:01 UTC, Renvel19 requested changes

2024-11-09 18:01 UTC, Renvel19 commented on app/src/main/java/co/edu/uniandes/vinilos/screens/ArtistListScreen.kt
> +        showBackIcon = true,
Acá falta redireccionar a la pantalla anterior, al darle en la flecha lleva a seleccionar perfil nuevamente, esto no debería ser así.

2024-11-09 18:01 UTC, Renvel19 commented on app/src/main/java/co/edu/uniandes/vinilos/screens/ArtistListScreen.kt
> +    val formattedDate = formatBirthDate(artist.birthDate)
Los artistas debería aparecer en la parte superior de la pantalla, no en la mitad, independientemente de la cantidad de artistas que se están mostrando

2024-11-09 18:01 UTC, Renvel19 commented on app/src/main/java/co/edu/uniandes/vinilos/screens/ArtistListScreen.kt
> +    Card(
La Card no se ve como lo propusimos en el figma, está muy pequeña, sería bueno si logramos agrandarla un poco,  también falta el icono al lado de la fecha. La idea es hacerla lo más parecida al figma

2024-11-13 02:39 UTC, lordmkichavi-andes commented on app/src/main/java/co/edu/uniandes/vinilos/screens/ArtistListScreen.kt
> +    Card(
ajustada a la propuesta

2024-11-13 02:39 UTC, lordmkichavi-andes commented on app/src/main/java/co/edu/uniandes/vinilos/screens/ArtistListScreen.kt
> +    val formattedDate = formatBirthDate(artist.birthDate)
ajustado al  diseño.

2024-11-13 02:39 UTC, lordmkichavi-andes commented on app/src/main/java/co/edu/uniandes/vinilos/screens/ArtistListScreen.kt
> +        showBackIcon = true,
ajustada lka navegacion

2024-11-13 02:40 UTC, lordmkichavi-andes reviewed
ajustados los comentarios

2024-11-13 02:43 UTC, Renvel19 approved these changes

2024-11-13 02:47 UTC, merged